package com.taotao.mapper;


import com.taotao.pojo.ContentCategory;
import tk.mybatis.mapper.common.Mapper;

public interface ContentCategoryMapper extends Mapper<ContentCategory> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content_category
     *
     * 
     */
    int insert(ContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content_category
     *
     * 
     */
    int insertSelective(ContentCategory record);
}