package com.taotao.mapper;


import com.taotao.pojo.ItemParamItem;
import tk.mybatis.mapper.common.Mapper;

public interface ItemParamItemMapper extends Mapper<ItemParamItem> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param_item
     *
     * 
     */
    int insert(ItemParamItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param_item
     *
     * 
     */
    int insertSelective(ItemParamItem record);
}