package com.taotao.mapper;


import com.taotao.pojo.Item;
import tk.mybatis.mapper.common.Mapper;

public interface ItemMapper extends Mapper<Item> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * 
     */
    /*int insert(Item record);*/

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * 
     */
    int insertSelective(Item record);
}