package com.taotao.mapper;


import com.taotao.pojo.ItemParam;
import tk.mybatis.mapper.common.Mapper;

public interface ItemParamMapper extends Mapper<ItemParam> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * 
     */
    int insert(ItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * 
     */
    int insertSelective(ItemParam record);
}