package com.taotao.mapper;


import com.taotao.pojo.ItemDesc;
import tk.mybatis.mapper.common.Mapper;

public interface ItemDescMapper extends Mapper<ItemDesc> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * 
     */
    /*int insert(ItemDesc record);*/

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * 
     */
    int insertSelective(ItemDesc record);
}