package com.taotao.mapper;


import com.taotao.pojo.OrderShipping;
import tk.mybatis.mapper.common.Mapper;

public interface OrderShippingMapper extends Mapper<OrderShipping> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * 
     */
    /*int insert(OrderShipping record);*/

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * 
     */
    int insertSelective(OrderShipping record);
}